name = "healtharchive-feedback"
main = "src/index.js"
compatibility_date = "2026-07-01"

routes = [
  { pattern = "api.healtharchive.kr", custom_domain = true },
  { pattern = "m.healtharchive.kr", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "healtharchive-feedback"
database_id = "fcf56e1f-811f-4198-a5eb-c3f0e2cc87e4"

[[r2_buckets]]
binding = "PRIVATE_DATA"
bucket_name = "healtharchive-assets"

[[send_email]]
name = "ACCESS_NOTIFY"
destination_address = "healtharchive2026@gmail.com"
allowed_sender_addresses = ["no-reply@healtharchive.kr"]

[[send_email]]
name = "ACCESS_REPLY"
allowed_sender_addresses = ["no-reply@healtharchive.kr"]
